[POM-48] feat: Payment 도메인 구현
prgrms-be-devcourse/BE-04-PoMin pull request #27
Opened 2023-09-07 08:57 UTC by ddongpuri

2023-09-08 22:50 UTC, beomukim approved these changes
지연님 수고하셨습니다! 👍👍

2023-09-08 22:50 UTC, beomukim commented on build.gradle
> +    compileOnly 'org.projectlombok:lombok'
여기 indent 맞춰주세요!

2023-09-08 23:57 UTC, Juhongseok commented on .gitmodules
> +	url = https://github.com/Juhongseok/Pomin-Submodule
이 부분은 왜 수정이 이뤄진거죠?

2023-09-08 23:58 UTC, Juhongseok commented on src/main/java/com/ray/pomin/payment/domain/PGInfo.java
> +    this.payKey = payKey;
검증 로직이랑 할당하는 부분 사이에 빈 줄을 둬서 구분을 주면 더 좋을 것 같아요

2023-09-09 00:07 UTC, Juhongseok requested changes
gitmodules 파일 한번만 확인 부탁으려요

2023-09-09 06:07 UTC, ddongpuri commented on .gitmodules
> +	url = https://github.com/Juhongseok/Pomin-Submodule
저는 손댄적이 없는데 왜 수정이 이루어졌는지 모르겠네요..!?
[feat: .gitmodules 원상 복구](https://github.com/prgrms-be-devcourse/BE-04-PoMin/pull/27/commits/f55bdc8d1620ec58c5db96f8cc5851f4b079f6e2)

2023-09-09 06:07 UTC, ddongpuri commented on src/main/java/com/ray/pomin/payment/domain/PGInfo.java
> +    this.payKey = payKey;
[chore: 검증 코드와 값 할당 코드 사이 빈 줄 추가](https://github.com/prgrms-be-devcourse/BE-04-PoMin/pull/27/commits/3ed3a00583b76fbb654b737884ab3a4632b1cedd)

2023-09-11 03:29 UTC, Juhongseok approved these changes
👍

2023-09-11 03:41 UTC, choi5798 approved these changes
LGTM 👍

2023-09-11 03:45 UTC, merged