[POM-69] feat: 결제 취소 로직 구현
prgrms-be-devcourse/BE-04-PoMin pull request #49
Opened 2023-09-14 05:51 UTC by ddongpuri

## 📌 PR 설명
- 외부 api 연동이 필요해서 결제 데이터 생성 ~ 취소 요청 ~ DB 반영 테스트를 프론트에서 직접 값을 넘겨서 수행했습니다.
(테스트 코드는 추후에 추가하겠습니다)
- 결제 요청시 받은 orderId 를 통해 '결제요청 가능한 주문'인지 판단하는 로직은 주문로직 확인 후 추가 예정입니다.

2023-09-14 05:52 UTC, juno-junho approved these changes
👍

2023-09-14 05:53 UTC, juno-junho approved these changes

2023-09-14 05:53 UTC, juno-junho commented on src/main/java/com/ray/pomin/payment/service/PaymentService.java
>      headers.set("Content-Type", "application/json");
이거 MediaType.APPLICATION_JSON 인가 enum으로 제공하는 값이 있어서 그거 사옹해보세요
contentType도 setContentType 메서드 사용하면 좋습니다.

2023-09-14 05:54 UTC, juno-junho commented on src/main/java/com/ray/pomin/payment/service/PaymentService.java
> +    HashMap<String, String> paymentRequestInfo = new HashMap<>();
Map.of() 사용하는것도 괜찮을것 같아요

2023-09-14 08:12 UTC, ddongpuri commented on src/main/java/com/ray/pomin/payment/service/PaymentService.java
>      headers.set("Content-Type", "application/json");
[refactor: 코드 가독성 개선](https://github.com/prgrms-be-devcourse/BE-04-PoMin/pull/49/commits/0646ba2814eb0a6eec28d351c92b1a96f15f2f57)

2023-09-14 08:12 UTC, ddongpuri commented on src/main/java/com/ray/pomin/payment/service/PaymentService.java
> +    HashMap<String, String> paymentRequestInfo = new HashMap<>();
[refactor: 코드 가독성 개선](https://github.com/prgrms-be-devcourse/BE-04-PoMin/pull/49/commits/0646ba2814eb0a6eec28d351c92b1a96f15f2f57)

2023-09-14 12:40 UTC, Juhongseok commented on src/main/java/com/ray/pomin/payment/controller/PaymentController.java
> +                                            @RequestParam int amount) throws JsonProcessingException {
exception을 서비스 내부에서 처리를 하는 것도 좋아보이네요
비지니스 로직 상에서 발생한 내용이니

2023-09-14 12:42 UTC, Juhongseok commented on src/main/java/com/ray/pomin/payment/service/PaymentService.java
> +    final String url = "https://api.tosspayments.com/v1/payments/confirm";
왜 여기만 변수가 final 이죠???

2023-09-14 12:43 UTC, Juhongseok commented on src/main/java/com/ray/pomin/payment/service/PaymentService.java
>    }
이 메소드는 `createPaymentRequest()` 메소드 아래로 옮기는게 읽기 더 편할 거 같아요

2023-09-14 12:45 UTC, Juhongseok commented on src/main/java/com/ray/pomin/payment/service/PaymentService.java
> +    }
```suggestion
private PayType method() {
    if (payMethod == EASYPAY) {
       return PayType.findByTitle(jsonNode.get("easyPay").get("provider").textValue());
    }
    return PayType.findByCode(jsonNode.get("card").get("issuerCode").textValue());
}
 ```
이런식으로 분리 할 수 있겠네요

2023-09-14 12:47 UTC, Juhongseok requested changes
간단한 수정 사항들만 확인 해주세요

2023-09-14 13:04 UTC, beomukim approved these changes
지연님 수고하셨습니다~ 
하나 말씀드릴건 PaymentService 클래스가 너무 방대해진거 같아서 클래스 분리할 수 있는 부분이 있는지 한번 고려해보세요 restTemplate도 의존성 주입으로 받을 수 있을거 같네요 내일 한번 얘기해보시죠

2023-09-14 13:34 UTC, choi5798 approved these changes
👍

2023-09-15 00:04 UTC, hyeon-z approved these changes
👍

2023-09-15 03:55 UTC, ddongpuri commented on src/main/java/com/ray/pomin/payment/service/PaymentService.java
> +    }
[chore: 메서드 분리 및 순서변경, 불필요한 키워드 제거](https://github.com/prgrms-be-devcourse/BE-04-PoMin/pull/49/commits/32c1512d876752fac10ab17b21b6209f8c812d0a)

2023-09-15 03:55 UTC, ddongpuri commented on src/main/java/com/ray/pomin/payment/service/PaymentService.java
>    }
[chore: 메서드 분리 및 순서변경, 불필요한 키워드 제거](https://github.com/prgrms-be-devcourse/BE-04-PoMin/pull/49/commits/32c1512d876752fac10ab17b21b6209f8c812d0a)

2023-09-15 03:55 UTC, ddongpuri commented on src/main/java/com/ray/pomin/payment/service/PaymentService.java
> +    final String url = "https://api.tosspayments.com/v1/payments/confirm";
[chore: 메서드 분리 및 순서변경, 불필요한 키워드 제거](https://github.com/prgrms-be-devcourse/BE-04-PoMin/pull/49/commits/32c1512d876752fac10ab17b21b6209f8c812d0a)

2023-09-15 04:03 UTC, Juhongseok commented on src/main/java/com/ray/pomin/payment/service/PaymentService.java
> +  private static PayType getPayType(JsonNode jsonNode, PayMethod payMethod) {
static?

2023-09-15 04:03 UTC, Juhongseok approved these changes
👍

2023-09-15 04:12 UTC, merged