[POM-69] feat: PaymentService 역할 분리
prgrms-be-devcourse/BE-04-PoMin pull request #53
Opened 2023-09-16 01:52 UTC by ddongpuri

## 📌 PR 설명
- PaymentService 에서 PaymentGatewayHandler, PaymentGatewayResponseParser 분리
- Payment 클래스 BaseEntity 상속 제거 -> 정확한 결제일시를 기록하기 위해 ApprovedAt 추가 

##  📌 질문
- 아직 JsonProcessingException 를 어떤 방식으로 처리할지 결정하지 못했습니다. 조언주시면 감사하겠습니다!

2023-09-16 04:56 UTC, beomukim approved these changes
👍👍

2023-09-16 04:56 UTC, beomukim commented on src/main/java/com/ray/pomin/payment/service/PaymentGatewayResponseParser.java
> +@Slf4j
로깅을 하는 부분이 없는 것 같은데 어노테이션을 다신 이유가 있을까요?

2023-09-16 05:12 UTC, choi5798 approved these changes
이전보다 확실히 코드가 깔끔해 보이네요 👍

2023-09-16 05:12 UTC, choi5798 commented on src/main/java/com/ray/pomin/payment/domain/Payment.java
> +    validate(!isNull(approvedAt), "결제 일시는 필수 값입니다");
이중부정문을 안 쓰는 방향으로 검증을 해보면 어떨까요?

2023-09-16 12:03 UTC, juno-junho approved these changes
👍

2023-09-16 12:03 UTC, juno-junho commented on src/main/java/com/ray/pomin/payment/domain/Payment.java
> +@Getter
저희 팀 컨벤션 `@Getter` 써도 되나요?

2023-09-16 12:03 UTC, juno-junho commented on src/main/java/com/ray/pomin/payment/service/PaymentGatewayHandler.java
> +    private String secretKey;
이러면 불변이 깨지는데 Bean을 주입 받는 구조로 변경해보는건 어떨까요

2023-09-17 01:24 UTC, ddongpuri commented on src/main/java/com/ray/pomin/payment/service/PaymentGatewayResponseParser.java
> +@Slf4j
떼고 필요할 때 다시 붙이겠습니다!

2023-09-17 10:05 UTC, Juhongseok commented on src/main/java/com/ray/pomin/payment/domain/Payment.java
> +                    .status(paymentInfo.status())
도메인에서 dto를 의존하는 방향은 옳지않다고 생각이드네요

2023-09-17 10:06 UTC, Juhongseok commented on src/main/java/com/ray/pomin/payment/service/PaymentGatewayHandler.java
> +    PaymentInfo makePaymentRequest(String orderId, String paymentKey, int amount) throws JsonProcessingException {
이 메소드에서 예외를 비지니스 의미를 가지는 런타임 예외로 변환을 해도되고 추가적인 예외처리 로직을 작성해서 컨트롤러에 throw 절이 사라지면 좋겠네요

2023-09-17 10:07 UTC, Juhongseok requested changes
몇군데 수정해주세요

2023-09-17 10:44 UTC, hyeon-z approved these changes
👍

2023-09-17 10:48 UTC, hyeon-z commented on src/main/java/com/ray/pomin/payment/domain/Payment.java
> +@AllArgsConstructor
해당 어노테이션이 어디에서 쓰이고 있을까요??

2023-09-17 11:55 UTC, ddongpuri commented on src/main/java/com/ray/pomin/payment/domain/Payment.java
> +@AllArgsConstructor
@ Builder 를 사용하려면 필요해서 넣었습니다..!

2023-09-17 15:39 UTC, ddongpuri commented on src/main/java/com/ray/pomin/payment/domain/Payment.java
> +                    .status(paymentInfo.status())
[fix: paymentInfo에 대한 의존성 제거](https://github.com/prgrms-be-devcourse/BE-04-PoMin/pull/53/commits/724a192d88647c3bc08254f62b8d2dc8b99cdd4e)

2023-09-17 15:40 UTC, ddongpuri commented on src/main/java/com/ray/pomin/payment/service/PaymentGatewayHandler.java
> +    PaymentInfo makePaymentRequest(String orderId, String paymentKey, int amount) throws JsonProcessingException {
[fix: JsonProcessiongException 처리](https://github.com/prgrms-be-devcourse/BE-04-PoMin/pull/53/commits/280bdac00993f2e7acbcf62e8b79f71541b41774)

2023-09-18 03:31 UTC, Juhongseok approved these changes
👍

2023-09-18 04:10 UTC, merged